Create change-password template
jdomingu98/ft_transcendence_backend pull request #11
Opened 2024-07-02 16:54 UTC by crist6494

2024-07-02 22:15 UTC, jdomingu98 requested changes
Esto no es lo que se pide. En esta tarea se pide un código html para el cuerpo de un email, pero por lo que he visto parece más la página a la que te lleva el email.

En caso de que haya acertado, aun así no sigue con los estilos generales de la web (el mockup de esa pantalla esta hecha recientemente porque era de este sprint). Me parece muy bien, por el contrario el uso del modal, puesto que será utíl para hacer los de la autenticación más adelante

2024-07-02 22:16 UTC, jdomingu98 commented
PD: Rellena correctamente las PR, te falta el label

2024-08-19 00:53 UTC, jdomingu98 commented
Optimizaciones:
- Importar tipografía Outfit en css
- Eliminado una etiqueta script inutil
- Eliminado un stylesheet inutil
- Añadido html semantico
- Eliminadas clases innecesarias

Mejoras:
- El texto de los parrafos se ha dividido en el codigo html para que sea más legible éste
- El gradiente eliminado y sustituido por un shadow box, ya que no quedaba del todo bien con el border-radius del card
- Nueva media query para pantallas intermedias-pequeñas
- Medidas que estaban en px ahora estan en rem para tema responsive y accesible
- Reducido el numero de reglas css
- Eliminada la imagen porque no aporta nada a la interfaz ni a la experiencia de usuario
- Nuevo titulo en el head, en lugar del por defecto "Document"
- Reorganizadas las carpetas y sus nombres, puesto que se tiene planteado en el futuro hacer otro template

2024-08-19 00:54 UTC, jdomingu98 approved these changes
Me apruebo a mi mismo, di que si

2024-08-19 00:55 UTC, jdomingu98 commented
Faltaria hacer la prueba en el cuerpo de un correo antes del mergeo

2024-08-19 16:36 UTC, ruzafa8 approved these changes
interesante 🗡️

2024-08-23 14:21 UTC, merged