Add JWT Access and Refresh Token Generation
jdomingu98/ft_transcendence_backend pull request #15
Opened 2024-08-06 18:57 UTC by Atrujillo02

2024-08-09 20:15 UTC, ruzafa8 requested changes
Bien, aunque hay un par de cosas que podríamos mejorar antes de cerrar la PR... La última vez que lo vimos no te dije nada pq tenía que repasarlo y ya vimos muchas cosas

2024-08-09 20:15 UTC, ruzafa8 commented on apps/user/v1/views.py
> +            return Response({"access_token": access_token, "refresh_token": new_refresh_token}, status=status.HTTP_200_OK)
Esto no es buena práctica de Django enviarlo sin serializador. Podríamos reutilizar el mismo serializador `LoginSerializer`, el cual tiene dos campos de momento:
 ```python
username = serializers.CharField()
password = serializers.CharField()
```

Podríamos añadir estos dos campos nuevos tal que así:
```python
username = serializers.CharField()
password = serializers.CharField()
access_token = serializers.CharField()
refresh_token = serializer.CharField()
```

¿Cúal es primer problema? Que no habría diferencia entre el JSON que recibe la petición del que devuelve... Ahora nos exigiría un access_token de entrada y un refresh_token de entrada, cosa que no tenemos, además de devolvernos de nuevo el username y la password!!! Cosa que es muy insegura... Para ello tenemos el "read_only" y el "write_only". Le pondremos write_only a los atributos que son de entrada y read_only a los que son de salida, tal que así:

```python
username = serializers.CharField(write_only=True)
password = serializers.CharField(write_only=True)
access_token = serializers.CharField(read_only=True)
refresh_token = serializer.CharField(read_only=True)
```

¿Ves así claro cuales son los parámetros de entrada y cuáles los de salida?

Segundo (y último problema) de esto:
- El Serializador tiene un "context". Es un objeto que tiene los valores que se van a usar para rellenar el JSON. Hay que ponerle al "context" de nuestro serializador los valores de access_token y refresh__token... Para esto hablame por fa y lo miramos juntos que así me va a costar explicartelo

2024-08-09 20:15 UTC, ruzafa8 commented on apps/user/v1/views.py
> +        return Response({"access_token": access_token, "refresh_token": new_refresh_token}, status=status.HTTP_200_OK)
Idem, no es buena práctica devolver esto así. Deberíamos de usar un serializador.

2024-08-21 14:27 UTC, jdomingu98 approved these changes
Yo te doy el ok, pero manda @ruzafa8

2024-08-21 14:51 UTC, ruzafa8 approved these changes

2024-08-21 17:07 UTC, merged