Create statistics table
jdomingu98/ft_transcendence_backend pull request #5
Opened 2024-06-26 19:59 UTC by crist6494

2024-06-27 06:30 UTC, ruzafa8 commented
Te salen mis cambios porque he mergeado a betta y te tienes que traer los cambios a tu rama:

git checkout betta; git pull; git checkout feature/TR-53/Crear-tabla-estadisticas-BBDD; git merge betta;

2024-06-28 17:20 UTC, Atrujillo02 commented on apps/game/migrations/0001_initial.py
todavía te salen los cambios de alex

2024-06-28 17:20 UTC, Atrujillo02 commented on apps/user/models.py
borra los espacios vacíos

2024-06-28 17:53 UTC, ruzafa8 requested changes
al aplicar cambios sobre el modelo creo que te va a generar nuevas migraciones, subelas también please :)

2024-06-28 17:53 UTC, ruzafa8 commented on apps/game/models.py
> +    user_id = models.OneToOneField('user.User', on_delete=models.CASCADE)
debería de llamarse user

2024-06-28 17:53 UTC, ruzafa8 commented on apps/game/models.py
> +    max_streak = models.IntegerField()
Todos estos campos, que son Integer, son obligatorios al no tener el null=False, pero es recomendable ponerle un default por si no le pasamos nada. Por ejemplo,creo que todos estos campos, si no especificamos nada podríamos suponer que son 0.

2024-06-28 18:28 UTC, ruzafa8 commented on apps/user/models.py
![image](https://github.com/jdomingu98/ft_transcendence_backend/assets/34567477/3ac5d6dc-9aaa-471f-a1ee-0b5eda005df2)
borra borra

2024-06-30 12:12 UTC, ruzafa8 approved these changes

2024-06-30 12:12 UTC, ruzafa8 commented on apps/game/migrations/0001_initial.py
ya no 👯‍♂️

2024-06-30 19:10 UTC, jdomingu98 requested changes

2024-06-30 19:10 UTC, jdomingu98 commented on apps/game/models.py
> +    tournament_win_rate = models.IntegerField(default=0)
Tendria más sentido poner que al crear la cuenta tengas un 100% de winrate no?

Además deberia estar limitado el campo a valores del 1 al 100.

2024-06-30 19:10 UTC, jdomingu98 commented on apps/game/models.py
> +    invididual_win_rate = models.IntegerField(default=0)
Aqui tambien

2024-06-30 19:10 UTC, jdomingu98 commented on apps/game/models.py
> +    time_played = models.TimeField(default=None)
quita lo del none default

2024-07-01 15:47 UTC, ruzafa8 commented on apps/game/models.py
> +    tournament_win_rate = models.IntegerField(default=0)
se le puede indicar que como mucho sean 3 dígitos, el min value y el max value

2024-07-01 15:50 UTC, ruzafa8 commented on apps/game/models.py
> +    time_played = models.TimeField(default=None)
si, poner default=None es lo mismo que no poner nada, así que en este caso es preferible no ponerlo.

Podría darse el caso en el que queramos hacer explícito que vale None, por si fuera algo excepcional o crítico, pero en este caso es preferible no indicarlo

2024-07-02 17:10 UTC, crist6494 commented on apps/game/models.py
> +    time_played = models.TimeField(default=None)
vale es que había mirado que el tiempo era mejor  ponerlo así en vez de 0, lo pongo a 0 o lo dejo vacio?

2024-07-02 19:55 UTC, jdomingu98 commented on apps/game/models.py
> +    time_played = models.TimeField(default=None)
vacio

2024-07-02 19:55 UTC, jdomingu98 commented on apps/game/models.py
> +    time_played = models.TimeField(default=None)
Osea lo del none es que es redundante

2024-07-02 22:22 UTC, jdomingu98 requested changes
Los cambios ahora son correctos, pero te voy a hacer lo mismo que con Ale en la rama del endpoint del inicio de sesion.

Los 3 ultimos commit se pueden hacer en uno solo con un mejor nombre. Vas a volver 3 commits hacia atras, vas a realizar los mismos cambios de los siguientes commits en uno solo y le vas a poner un mejor mensajes.

Ya pase un par de enlaces por el grupo que sirve para hacer mejores commits, uno de teoria y otro que te ayuda a montarlo.

2024-07-02 22:24 UTC, jdomingu98 commented
Para volver hacia atras: git reset --hard HEAD~3

El comando sobre esta rama

2024-07-03 17:32 UTC, closed without merging