user game history endpoint
jdomingu98/ft_transcendence_backend pull request #57
Opened 2024-11-04 18:22 UTC by Atrujillo02

2024-11-04 18:23 UTC, Atrujillo02 commented
Esto es lo que mando al front pag1->
![pag1](https://github.com/user-attachments/assets/ccecc0ad-b057-439b-8984-381e6fa04585)
y esta seria la ultima pagina 4->
![pag4](https://github.com/user-attachments/assets/68f5357a-5a27-4292-b257-a2d94641d1d8)

2024-11-04 18:42 UTC, jdomingu98 commented
Esos datos no son los que hacen falta en el front. Ya dije varias veces que la categoria del historial de partidas hay que actualizarla en el front para que muestre estadisticas locales.

Te comenté también un par de veces que los datos que necesito son literalmente los de la tabla de local_match, es decir:
{ user_b, start_date, num_goals_scored, num_goals_against, num_goals_stopped_a, num_goals_stopped_b, time_played }

Como al ganar, perder o empatar los puntos que cambian el total son los mismos, pues en principio no me hace falta. El id tampoco me hace falta porque no redirecciono a ningun lado.

Por otro lado, los resultados tienen que estar ordenados de más reciente a más antiguo

Por último, el formato de time_played debería ser como el del time_played de la tabla de estadisticas (algo tipo 0m 0s) y el start_date debería tener un formato tipo "dd/MM/yyyy hh:mm:ss" (aunque en ingles y chino el formato es diferente, pero esto lo obviamos)

2024-11-04 23:44 UTC, jdomingu98 requested changes
El comentario anterior mio

2024-11-05 09:50 UTC, jdomingu98 commented on backend/utils/match.py
> +    matches = fetch_user_matches(user_id)
la funcion fetch_user_matches no es necesaria, puesto que son dos lineas. Ponlas directamente aquí

2024-11-05 09:50 UTC, jdomingu98 commented on backend/utils/match.py
> +    return LocalMatch.objects.filter(Q(user_a=user) | Q(user_b=user))
Si el usuario esta logueado siempre va a ser el user_a. user_b nunca va a tener cuenta

2024-11-05 09:50 UTC, jdomingu98 commented on backend/utils/match.py
> +    user = get_object_or_404(User, pk=user_id)
Si el usuario no está logueado y quiere jugar una partida local me da un 404? Pregunto porque no se que hace esta función exactamente

2024-11-05 09:50 UTC, jdomingu98 commented on apps/user/v1/views.py
> +        return get_user_matches(pk, request)
Todo lo de get_user_matches lo pondría aquí

2024-11-05 09:50 UTC, jdomingu98 commented on apps/user/v1/serializers.py
> +    def get_result(self, obj):
Lo mismo más corto

```python
    def get_result(self, obj):
        result = 'victory' if obj.num_goals_scored > obj.num_goals_against else 'defeat'
        if obj.num_goals_scored == obj.num_goals_against:
            result = 'draw'
       return result
```

2024-11-05 09:50 UTC, jdomingu98 commented on apps/user/v1/serializers.py
> +    def get_earned(self, obj):
Lo mismo más corto
```python
    def get_earned(self, obj):
        points = 10 if obj.num_goals_scored > obj.num_goals_against else -5
        if obj.num_goals_scored == obj.num_goals_against:
            points = 0
       return points
```

2024-11-05 09:50 UTC, jdomingu98 commented on backend/utils/match.py
> +    page_size = 5
Si solo se usa una vez y siempre es el mismo valor, ponlo directamente en el sitio

2024-11-05 10:35 UTC, Atrujillo02 commented on backend/utils/match.py
> +    user = get_object_or_404(User, pk=user_id)
Exactamente si no esta en la base de datos te da 404. Puedes tener un perfil para ver tu historial de partidas sin estar registrado?

2024-11-05 10:36 UTC, Atrujillo02 commented on apps/user/v1/views.py
> +        return get_user_matches(pk, request)
Era para tener una view mas pequeña y ordenada pero lo cambio ahora mismito

2024-11-05 10:37 UTC, Atrujillo02 commented on apps/user/v1/serializers.py
> +    def get_result(self, obj):
Ya no va a hacer falta si tengo que devolver esto { user_b, start_date, num_goals_scored, num_goals_against, num_goals_stopped_a, num_goals_stopped_b, time_played }

2024-11-05 10:37 UTC, Atrujillo02 commented on apps/user/v1/serializers.py
> +    def get_earned(self, obj):
Ya no va a hacer falta si tengo que devolver esto { user_b, start_date, num_goals_scored, num_goals_against, num_goals_stopped_a, num_goals_stopped_b, time_played }

2024-11-05 10:38 UTC, Atrujillo02 commented on backend/utils/match.py
> +    page_size = 5
Ese es el sitio eso es una clase que hereda de PageNumberPagination (función de django) la estoy redefiniendo.

2024-11-05 11:44 UTC, Atrujillo02 commented
Ya he cambiado todo lo que me dijiste lo que devuelve, el orden y he modificado el código como me has dicho. :)
Paso una foto de lo que devuelvo ahora
![pag1](https://github.com/user-attachments/assets/31d4aea0-4a79-4827-a311-c691031859af)

2024-11-05 12:37 UTC, jdomingu98 commented on backend/utils/match.py
> +    user = get_object_or_404(User, pk=user_id)
Ah cierto, que esto es para ver resultados, estaba pensando en el registro de partidas por la cara xD

2024-11-05 12:37 UTC, jdomingu98 commented on apps/user/v1/serializers.py
> +    def get_result(self, obj):
cierto

2024-11-05 12:38 UTC, jdomingu98 commented on backend/utils/match.py
> +    page_size = 5
ah vale vale

2024-11-05 12:39 UTC, jdomingu98 commented on apps/user/v1/serializers.py
> +    def get_earned(self, obj):
cierto

2024-11-05 12:40 UTC, jdomingu98 commented on apps/user/v1/serializers.py
> +    def get_result(self, obj):
No vendría mal tenerlo, pero lo puedo hacer en el front tambien

2024-11-05 12:46 UTC, jdomingu98 commented
@Atrujillo02  lo del time_played sigue sin tener el formato correcto, osea tiene de valor algo como 00:00:00.
¿Eso es horas, minutos y segundos o minutos, segundos y milisegundos? yo quiero que sea minutos y segundos solamente

Con el start_date ya no es necesario en principio, ya que el chatgpt me ha dado una alternativa de parseo en el front, asi podriamos tener el formato correcto de fecha segun el idioma

2024-11-05 14:18 UTC, Atrujillo02 commented
Ahora si en minutos y segundos.
![time_played](https://github.com/user-attachments/assets/77c09cba-0781-44d6-a872-f122ab8989b6)

2024-11-05 16:48 UTC, jdomingu98 commented
@Atrujillo02 el limite del time_played esta puesto en 5 minutos?

2024-11-05 16:53 UTC, jdomingu98 approved these changes

2024-11-05 16:53 UTC, ruzafa8 approved these changes

2024-11-05 16:56 UTC, merged